export const FONTS = [
  { name: 'Inter', value: '"Inter", sans-serif' },
  { name: 'Arial', value: 'Arial, sans-serif' },
  { name: 'Helvetica Neue', value: '"Helvetica Neue", Arial, sans-serif' },
  { name: 'Georgia', value: 'Georgia, serif' },
  { name: 'Courier New', value: '"Courier New", Courier, monospace' },
  { name: 'Roboto', value: '"Roboto", sans-serif' },
  { name: 'Open Sans', value: '"Open Sans", sans-serif' },
  { name: 'Lato', value: '"Lato", sans-serif' },
  { name: 'Montserrat', value: '"Montserrat", sans-serif' },
  { name: 'Oswald', value: '"Oswald", sans-serif' },
  { name: 'Source Sans Pro', value: '"Source Sans Pro", sans-serif' },
  { name: 'Raleway', value: '"Raleway", sans-serif' },
  { name: 'PT Sans', value: '"PT Sans", sans-serif' },
  { name: 'Noto Sans', value: '"Noto Sans", sans-serif' },
  { name: 'Nunito', value: '"Nunito", sans-serif' },
  { name: 'Ubuntu', value: '"Ubuntu", sans-serif' },
  { name: 'Playfair Display', value: '"Playfair Display", serif' },
  { name: 'Merriweather', value: '"Merriweather", serif' },
  { name: 'Lora', value: '"Lora", serif' },
  { name: 'PT Serif', value: '"PT Serif", serif' },
  { name: 'Noto Serif', value: '"Noto Serif", serif' },
  { name: 'Titillium Web', value: '"Titillium Web", sans-serif' },
  { name: 'Muli', value: '"Muli", sans-serif' },
  { name: 'Inconsolata', value: '"Inconsolata", monospace' },
  { name: 'Fira Sans', value: '"Fira Sans", sans-serif' },
  { name: 'Dosis', value: '"Dosis", sans-serif' },
  { name: 'Quicksand', value: '"Quicksand", sans-serif' },
  { name: 'Cabin', value: '"Cabin", sans-serif' },
  { name: 'Lobster', value: '"Lobster", cursive' },
  { name: 'Anton', value: '"Anton", sans-serif' },
  { name: 'Mukta', value: '"Mukta", sans-serif' },
  { name: 'Abel', value: '"Abel", sans-serif' },
  { name: 'Dancing Script', value: '"Dancing Script", cursive' },
  { name: 'Pacifico', value: '"Pacifico", cursive' },
  { name: 'Varela Round', value: '"Varela Round", sans-serif' },
  { name: 'Hind', value: '"Hind", sans-serif' },
  { name: 'Arimo', value: '"Arimo", sans-serif' },
  { name: 'Bitter', value: '"Bitter", serif' },
  { name: 'Oxygen', value: '"Oxygen", sans-serif' },
  { name: 'Crimson Text', value: '"Crimson Text", serif' },
  { name: 'Bree Serif', value: '"Bree Serif", serif' },
  { name: 'Karla', value: '"Karla", sans-serif' },
  { name: 'Josefin Sans', value: '"Josefin Sans", sans-serif' },
  { name: 'Yanone Kaffeesatz', value: '"Yanone Kaffeesatz", sans-serif' },
  { name: 'Asap', value: '"Asap", sans-serif' },
  { name: 'Libre Baskerville', value: '"Libre Baskerville", serif' },
  { name: 'Archivo Narrow', value: '"Archivo Narrow", sans-serif' },
  { name: 'Crete Round', value: '"Crete Round", serif' },
  { name: 'EB Garamond', value: '"EB Garamond", serif' },
  { name: 'Arvo', value: '"Arvo", serif' },
  { name: 'Cormorant Garamond', value: '"Cormorant Garamond", serif' },
  { name: 'Kanit', value: '"Kanit", sans-serif' },
  { name: 'Teko', value: '"Teko", sans-serif' }
];

export const GOOGLE_FONTS_URL = () => {
  const families = FONTS.map(f => f.name).filter(n => !['Arial', 'Helvetica Neue', 'Georgia', 'Courier New'].includes(n)).map(n => n.replace(/ /g, '+'));
  return `https://fonts.googleapis.com/css2?family=${families.join('&family=')}&display=swap`;
};
